'use client';

import { useAppDispatch, useAppSelector } from '@/store';
import { addOne, initCounterState, subtractOne } from '@/store/counter/counterSlice';
import { useEffect } from 'react';

interface Props {
  value?: number;
}

// Generated by https://quicktype.io

export interface CounterResponse {
  count: number;
}

async function getApiCounter(): Promise<CounterResponse> {
  return await fetch('/api/counter').then((res) => res.json());
}

export function CartCounter({ value = 0 }: Props) {
  const dispatch = useAppDispatch();
  const count = useAppSelector((state) => state.counter.count);

  useEffect(() => {
    getApiCounter().then((data) => {
      dispatch(initCounterState(data.count));
    });
  }, [dispatch]);

  return (
    <>
      <span className='text-9xl'>{count}</span>
      <div className='flex gap-2'>
        <button
          className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px]'
          onClick={() => dispatch(subtractOne())}
        >
          -1
        </button>
        <button
          className='flex items-center justify-center p-2 rounded-xl bg-gray-900 text-white hover:bg-gray-600 transition-all w-[100px]'
          onClick={() => dispatch(addOne())}
        >
          +1
        </button>
      </div>
    </>
  );
}
